missing repo debug

diff --git a/.github/workflows/cli.yml b/.github/workflows/cli.yml
--- a/.github/workflows/cli.yml
+++ b/.github/workflows/cli.yml
@@ -74,11 +74,10 @@ jobs:
         env:
           REPO_PATH: ${{ github.workspace }}
 
-
       - name: Install Python and MkDocs
         run: |
           python -m pip install --upgrade pip
-          pip install mkdocs-material  # Installiert MkDocs und das Material-Theme
+          pip install mkdocs-material
 
       - name: Build Documentation
         run: mkdocs build
@@ -89,6 +88,11 @@ jobs:
           mkdir -p deploy/repo
           mkdir -p deploy/docs
           mkdir -p deploy/download
+
+          if [ ! -d "installer/repo" ]; then
+            echo "ERROR: installer/repo missing! Aborting deploy."
+            exit 1
+          fi
           
           [ -d "installer/repo" ] && cp -r installer/repo/* deploy/repo/
           [ -d "site" ] && cp -r site/* deploy/docs/
